parameters:
#    viajes.example.class: Viajes\ViajesBundle\Example

services:
#    viajes.example:
#        class: %viajes.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
