parameters:
#    usuario.example.class: Viajes\UsuariosBundle\Example

services:
#    usuario.example:
#        class: %usuario.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
